crew:
  orchestrator:
    model: o4-mini-2025-04-16
  chief_architect:
    model: o4-mini-2025-04-16
  core_eng_1:
    model: o4-mini-2025-04-16
  core_eng_2:
    model: o4-mini-2025-04-16
  qa_perf:
    model: gpt-4.1-mini-2025-04-14
  devops:
    model: o4-mini-2025-04-16
  cost_analyst:
    model: gpt-3.5-turbo-0125
