name: Orchestrator
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with: {python-version: '3.11'}
      - run: pip install -r requirements.txt
      - run: python orchestrator.py
        env:
          GH_PAT: ${{ secrets.GH_PAT }}
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
